<?php

# SERVER TYPE DEFINITION
define('SERVER_TYPE_STANDALONE', 1);
define('SERVER_TYPE_ANODE', 1);
define('SERVER_TYPE_APPLIANCE', 2);
define('SERVER_TYPE_CLUSTER', 3);

define('SERVER_PLATFORM_SSH_INACTIVE', 0);
define('SERVER_PLATFORM_SSH_AUTH_TYPE_PASSWORD', 1);
define('SERVER_PLATFORM_SSH_AUTH_TYPE_KEY', 2);

define('SERVER_STATUS_PROVISIONING', 0);
define('SERVER_STATUS_RUNNING', 1);
define('SERVER_STATUS_SUSPENDED', 2);
define('SERVER_STATUS_DELETED', 3);

define('CLUSTER_STATUS_PROVISIONING', 0);
define('CLUSTER_STATUS_RUNNING', 1);
define('CLUSTER_STATUS_SUSPENDED', 2);
define('CLUSTER_STATUS_DELETED', 3);

?>