version: '3.0'
services:
    gateway:
      image: nginx:1.17.6
      ports:
        # - 80:80/tcp
        - 443:443/tcp
        - 3305:3305/tcp
        - 8080:8080/tcp
      volumes:
        - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/log:/var/log/nginx
        - ./certs:/opt/certs
      stdin_open: true
      depends_on:
        - application
        - phpmyadmin
      tty: true
      restart: always

    application:
        image: registry.docker.convesio.com:5005/v4/application/v4-controller-base-image:laravel.1.1
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        links:
            - pxc:pxc
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_HOST: pxc
            DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - '.:/var/www/html'
            - /opt/nginx:/nginx
            - /tmp/work:/tmp/work
            - ./certs:/opt/certs
        ports:
          - 5173:5173/tcp
        #   - 89:80/tcp
        depends_on:
            - pxc

    pxc:
      image: mariadb:10.4.10-bionic
      environment:
        MYSQL_DATABASE: application
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      restart: always
      volumes:
        - /opt/components/controller/mysql:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      links:
        - pxc:db
      ports:
        - 3307:80/tcp
      environment:
        PMA_HOST: pxc
      restart: always
